WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff8302ddc0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session
WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff8302dfa0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session
WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff8302d820>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session