{
  "e73ad7f62c87f3c5a5f5c989fd62271d" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "33e56ea5e05e6e97",
      "reportUrl" : "https://humanlanguage1.github.io/Demo-PyTest/37//#testresult/33e56ea5e05e6e97",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='*.blob.core.windows.net', port=80): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff8302d1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))",
      "time" : {
        "start" : 1646666301892,
        "stop" : 1646666301892,
        "duration" : 0
      }
    } ]
  },
  "482db84196fd973eefafc30f76b7e00a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "ed13bd9c8f9ed40d",
      "reportUrl" : "https://humanlanguage1.github.io/Demo-PyTest/37//#testresult/ed13bd9c8f9ed40d",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='*.blob.core.windows.net', port=80): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff82ac7070>: Failed to establish a new connection: [Errno -2] Name or service not known'))",
      "time" : {
        "start" : 1646666302155,
        "stop" : 1646666302155,
        "duration" : 0
      }
    } ]
  }
}